server:
  port: 10030

spring:
  application:
    name: jenkins-service-consumer

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone:  http://192.168.1.11:10010/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}