def git_auth = "83517f2b-5745-4cef-83a2-fcae7f6123cf"
def git_url = "git@github.com:xinyugitstudy/jenkins-springcloud-docker.git"
node {
 stage('拉取代码') {
  checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']], extensions: [],
   userRemoteConfigs: [[credentialsId: "${git_auth}", url: "${git_url}"]]])
 }
}