def git_auth = "83517f2b-5745-4cef-83a2-fcae7f6123cf"
def git_url = "git@github.com:xinyugitstudy/jenkins-springcloud-docker.git"
def harbor_url = "192.168.1.13:85/jenkins-springcloud-docker/"
//构建版本的名称
def tag = "latest"
node {
 stage('拉取代码') {
  checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']], extensions: [],
   userRemoteConfigs: [[credentialsId: "${git_auth}", url: "${git_url}"]]])
 }
 stage('编译，构建镜像') {
  //定义镜像名称
  def imageName = "${project_name}:${tag}"
  //编译，安装公共工程
  sh "mvn -f jenkins-commons clean install"
  //编译，构建本地镜像
  sh "mvn -f ${project_name} clean package dockerfile:build"
 }
}